#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jun 03, 2018 10:50:55 AM
import sys
import _pickle as pickle
import os
from tkinter import messagebox

from GUI.main_v1 import global_filepath
from Main import run_screening
from Utils.news_utils import NewsUtils

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = 0
except ImportError:
    import tkinter.ttk as ttk

    py3 = 1

# TODO ev in config file -->  gui load
# immer ins main kopieren
# global ROOT_DIR
# ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
# global global_filepath
# global_filepath = ROOT_DIR + '\\DataFiles\\'
# #TODO vom dataprovider lesen und dann zuweisen (irgendeine aktie abfragen)
# global glob_stock_data_labels_dict
# glob_stock_data_labels_dict = {'High': 'high', 'Low':'low', 'Open':'open',
#                                'Close':'close', 'Volume':'volume'}

class MyController:
    def __init__(self, parent):
        self.parent = parent
        self.model = MyModel(self)  # initializes the model
        self.view = w  # initializes the view
        # self.view.Match.config(command=self.all_parameter_dicts_changed)
        self.view.ButtonRunStrategy.config(command=self.start_screening)
        self.view.Scrolledlistbox_selectStrategy.bind('<<ListboxSelect>>', self.listbox_onselect)
        self.all_parameter_dicts_changed()
        self.available_strategies_changed()
        self.load_parameter_from_file()

    def start_screening(self):
        selection_value = self.model.get_strategy_selection_value()

        if selection_value == "" or len(selection_value) <= 0:
            messagebox.showerror("Selection Error", "Please select a strategy first!")
        else:
            # messagebox.showerror("Not Implemented Error", "Run not implemented yet")
            selected_strategy_params = self.model.get_all_parameter_dicts()[selection_value]
            stock_data_container_file_name = "stock_data_container_file.pickle"
            stock_data_container_file = global_filepath + stock_data_container_file_name
            last_date_time_file = global_filepath + "last_date_time.csv"
            data_source = 'iex'
            weeks_delta = 52  # one year in the past
            other_params = {'stock_data_container_file': stock_data_container_file, 'weeks_delta': weeks_delta,
                            'data_source': data_source, 'last_date_time_file': last_date_time_file}
            results = run_screening(selection_value, selected_strategy_params, other_params)
            self.model.extend_result_stock_data_container_list(results)


    def load_parameter_from_file(self):
        self.model.clear_all_parameter_dicts()
        self.model.clear_list()

        try:
            with open(global_filepath + "ParameterFile.pickle", "rb") as f:
                items = pickle.load(f)
                self.model.add_to_all_parameter_dicts(items)
                for item in items:
                    self.model.add_to_available_strategies(item)

        except Exception as e:
            print(str(e))
            return

        self.model.add_to_log("Params Read")

    def dump_parameter_from_file(self):
        content = self.view.Scrolledtext_params.get(1.0, END)
        import ast
        content_dict = ast.literal_eval(content)

        if content_dict == {}:
            messagebox.showerror("Parameters empty", "Please insert parameters")
        else:
            self.model.add_to_all_parameter_dicts(content_dict)
            with open(global_filepath + "ParameterFile.pickle", "wb") as f:
                pickle.dump(self.model.all_parameter_dicts, f)

            self.model.add_to_log("Params Saved")

    # event handlers
    def quitButtonPressed(self):
        self.parent.destroy()

    def add_button_pressed(self):
        self.model.add_to_available_strategies(self.view.entry_text.get())
        self.model.add_to_all_parameter_dicts({self.view.entry_text.get(): self.view.entry_text.get()})

    def clear_button_pressed(self):
        self.model.clear_list()

    def all_parameter_dicts_changed(self):
        w.Scrolledtext_params.delete(1.0, END)
        # model internally chages and needs to signal a change
        #TODO 11:
        test = self.model.get_all_parameter_dicts()
        w.Scrolledtext_params.insert(END, str(test))
        #for key, value in test.items():
        #    w.Scrolledtext_params.insert(END, "{'" + key + "':" + str(value) + "}")
        #    w.Scrolledtext_params.insert(END, "\n")

    def log_changed_delegate(self):
        w.Scrolledtext_log.delete(1.0, END)
        test = self.model.get_log()
        for t in test:
            w.Scrolledtext_log.insert(END, t)
            w.Scrolledtext_log.insert(END, "\n")

    def available_strategies_changed(self):
        w.Scrolledlistbox_selectStrategy.delete(0, END)
        # model internally chages and needs to signal a change
        available_strategies_list = self.model.getList()
        for available_strategy in available_strategies_list:
            w.Scrolledlistbox_selectStrategy.insert(END, available_strategy)

    def result_stock_data_container_list_changed(self):
        w.Scrolledtext_Results.delete(1.0, END)
        # model internally chages and needs to signal a change
        stock_data_container_list = self.model.get_result_stock_data_container_list()
        print_str = NewsUtils.format_news_analysis_results(stock_data_container_list)
        w.Scrolledtext_Results.insert(END, print_str)

    def add_available_indices(self):
        # w.Text1.update(str({'w52hi_parameter_dict': {'check_days': 7, 'min_cnt': 3, 'min_vol_dev_fact': 1.2, 'within52w_high_fact': 0.98}}))
        # w.Text1.insert(END, 'test')
        w.Scrolledlistbox1.insert(END, 'test')

    def listbox_onselect(self, evt):
        # Note here that Tkinter passes an event object to listbox_onselect()
        w = evt.widget
        index = int(w.curselection()[0])
        value = w.get(index)
        print('You selected item %d: "%s"' % (index, value))
        self.model.set_strategy_selection_value(value)


class MyModel:
    def __init__(self, vc):
        self.vc = vc
        self.available_strategies = [] #TODO ["SimplePatternNewsStrategy", "W52HighTechnicalStrategy"]
        #TODO verwenden
        self.program_parameter_dict = {'data_source': 'iex', 'weeks_delta': 52}
        self.all_parameter_dicts = {}
        w52hi_parameter_dict = {'check_days': 7, 'min_cnt': 3, 'min_vol_dev_fact': 1.2, 'within52w_high_fact': 0.98}
        parameter_dict = {'news_threshold': 0.7, 'german_tagger': global_filepath + 'nltk_german_classifier_data.pickle'}
        #self.all_parameter_dicts = {'W52HighTechnicalStrategy': w52hi_parameter_dict, "SimplePatternNewsStrategy": parameter_dict}
        self.log_text = []
        self.strategy_selection_value = ""
        self.result_stock_data_container_list = []

    def get_result_stock_data_container_list(self):
        return self.result_stock_data_container_list

    def clear_result_stock_data_container_list(self):
        self.result_stock_data_container_list = []
        self.vc.result_stock_data_container_list_changed()

    def extend_result_stock_data_container_list(self, stock_data_container_list):
        self.result_stock_data_container_list.extend(stock_data_container_list)
        self.vc.result_stock_data_container_list_changed()

    def set_strategy_selection_value(self, value):
        self.strategy_selection_value = value

    def get_strategy_selection_value(self):
        return self.strategy_selection_value

    # Delegates-- Model would call this on internal change
    def all_parameter_dicts_changed(self):
        self.vc.all_parameter_dicts_changed()

    # setters and getters
    def get_all_parameter_dicts(self):
        return self.all_parameter_dicts

    def add_to_all_parameter_dicts(self, items):
        for key, value in items.items():
            self.all_parameter_dicts.update({key: value})
        self.all_parameter_dicts_changed()

    def clear_all_parameter_dicts(self):
        self.all_parameter_dicts = {}
        self.all_parameter_dicts_changed()

    # Delegates-- Model would call this on internal change
    def list_changed(self):
        self.vc.available_strategies_changed()

    # setters and getters
    def getList(self):
        return self.available_strategies

    def add_to_available_strategies(self, item):
        myList = self.available_strategies
        myList.append(item)
        self.available_strategies = myList
        self.list_changed()

    def clear_list(self):
        self.available_strategies = []
        self.list_changed()

    def add_to_log(self, log_text):
        self.log_text.append(log_text)
        self.log_changed()

    def log_changed(self):
        self.vc.log_changed_delegate()

    def get_log(self):
        return self.log_text



def init(top, gui, *args, **kwargs):
    global w, top_level, root, app
    w = gui
    top_level = top
    root = top

    app = MyController(root)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def save():
    app.dump_parameter_from_file()


def quit():
    pass


def edit():
    pass


def load_params():
    app.load_parameter_from_file()


if __name__ == '__main__':
    import main_v1

    main_v1.vp_start_gui()
