#############################################################################
# Generated by PAGE version 4.9
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top32
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_4_0 .top32.tPa33.f1 
    set site_4_0 $site_4_0
    set site_5_0 $site_4_0.scr40
    set site_5_0 $site_4_0.scr42
    set site_4_1 .top32.tPa33.f2 
    set site_4_0 $site_4_1
    set site_5_0 $site_4_0.scr43
    set site_4_2 .top32.tPa33.f3 
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top32 {base} {
    if {$base == ""} {
        set base .top32
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 664x858+718+27
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "XYZ_Framework "
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TPanedwindow -background #d9d9d9
    ttk::style configure TPanedwindow.Label -background #d9d9d9
    ttk::style configure TPanedwindow.Label -foreground #000000
    ttk::style configure TPanedwindow.Label -font TkDefaultFont
    ttk::panedwindow $top.tPa33 \
        -width 585 -height 500 
    vTcl:DefineAlias "$top.tPa33" "TPanedwindow1" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa33.f1 \
        -text {Strategy parameter} -height -174.0 
    vTcl:DefineAlias "$top.tPa33.f1" "TPanedwindow1_f1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $top.tPa33.f1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr40 \
        -background {#d9d9d9} -height 155 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 581 

    $site_4_0.scr40.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr42 \
        -background {#d9d9d9} -height 131 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 581 
    vTcl:DefineAlias "$site_4_0.scr42" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr42.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_0.scr40 \
        -in $site_4_0 -x 0 -y 180 -width 581 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.scr42 \
        -in $site_4_0 -x 0 -y 20 -width 581 -relwidth 0 -height 131 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa33 add $top.tPa33.f1 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa33.f2 \
        -text {Result / Logging} -height 276 
    vTcl:DefineAlias "$top.tPa33.f2" "TPanedwindow1_f2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_1 $top.tPa33.f2
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_1.scr43 \
        -background {#d9d9d9} -height 211 -highlightbackground {#d9d9d9} \
        -highlightcolor black -width 581 
    vTcl:DefineAlias "$site_4_1.scr43" "st_logging" vTcl:WidgetProc "Toplevel1" 1

    $site_4_1.scr43.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_1.scr43 \
        -in $site_4_1 -x 0 -y 30 -width 581 -relwidth 0 -height 211 \
        -relheight 0 -anchor nw -bordermode ignore 
    $top.tPa33 add $top.tPa33.f2 
        
    ttk::style configure TLabelframe.Label -background #d9d9d9
    ttk::style configure TLabelframe.Label -foreground #000000
    ttk::style configure TLabelframe.Label -font TkDefaultFont
    ttk::style configure TLabelframe -background #d9d9d9
    ttk::labelframe $top.tPa33.f3 \
        -text {Results- Stocks} -height 104 
    vTcl:DefineAlias "$top.tPa33.f3" "TPanedwindow1_f3" vTcl:WidgetProc "Toplevel1" 1
    set site_4_2 $top.tPa33.f3
    $top.tPa33 add $top.tPa33.f3 
        
    button $top.but32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#b8a786} -foreground black \
        -highlightbackground wheat -highlightcolor black -pady 0 -text Match 
    vTcl:DefineAlias "$top.but32" "Match" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TSizegrip -background #d9d9d9
    vTcl::widgets::ttk::sizegrip::CreateCmd $top.tSi34 \
        -cursor size_nw_se 
    vTcl:DefineAlias "$top.tSi34" "TSizegrip1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tPa33 \
        -in $top -x 20 -y 10 -width 585 -relwidth 0 -height 730 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but32 \
        -in $top -x 50 -y 800 -anchor nw -bordermode ignore 
    place $top.tSi34 \
        -in $top -x 0 -relx 1 -y 0 -rely 1 -anchor se -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top32

