#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jan 05, 2018 10:23:07 PM


from StockScreening import run_stock_screening

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def display(p1):
    # Match Button
    print('main_v1_support.display')
    run_stock_screening(10) #TODO
    sys.stdout.flush()

def help():
    print('main_v1_support.help')
    sys.stdout.flush()

def load_regular_expression():
    print('main_v1_support.load_regular_expression')
    sys.stdout.flush()

def load_sample():
    print('main_v1_support.load_sample')
    sys.stdout.flush()

def quit():
    print('main_v1_support.quit')
    sys.stdout.flush()

def save_regular_expression():
    print('main_v1_support.save_regular_expression')
    sys.stdout.flush()

def save_sample():
    print('main_v1_support.save_sample')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    from GUI import main_v1

    main_v1.vp_start_gui()


